### PR TITLE
Wide angle brem conversion filter

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by omar-moreno** [comment]
Benchmark: 

Processed a file containing 1000 wide angle brem candidates with and without the pair conversion filter. The filter will only keep events that pair produce within the first three modules of the tracker.  For now, this is hard coded but will be changed to use regions once the HPS geometry model is modified to use regions. 

Without the filter: 
Run Timer: User=21.43s Real=21.48s Sys=0.04s
File size: 1.5 MB

With the filter: 
Run Timer: User=0.31s Real=0.33s Sys=0.02s
File size: 12 kB

**Comment by anongothdev** [comment]
Can you reformat your code with 4 space indents and revert the formatting changes to the other files?

The formatting changes to the files make it hard to see what you actually changed.

**Comment by anongothdev** [comment]
I didn't spot any changes to the files that weren't implementing the biasing. Do those need to be changes? (Looked like just formatting.)

**Review by JeremyMcCormick — APPROVED** [review]
These changes look good to me. Normal non-biased mode was checked and looked okay.

**Pull request merged**
